### PR TITLE
feat: update `Lean by Example`

### PR DESCRIPTION
**Pull request by Seasawher**
**What kind of change does this PR introduce?**

- [ ] Add a project
- [x] Update a project
- [ ] Remove a project
- [ ] Add or update a category
- [ ] Change configuration
- [ ] Documentation
- [ ] Other, please describe:

**Description:**

**Checklist:**

- [x] I have read the [CONTRIBUTING](https://github.com/best-of-lists/best-of/blob/main/CONTRIBUTING.md) guidelines.
- [x] I have not modified the `README.md` file. Projects are only supposed to be added or updated within the `projects.yaml` file since the `README.md` file is automatically generated.

### CODE REVIEW

**Comment by 34j** [comment]
説明文は途中で切られてしまうため1行内に収めた方が良いかもしれません

**Comment by Seasawher** [comment]
１行以内ではあると思います。文字数制限がありますか？

**Comment by 34j** [comment]
わかりませんが例えばこのくらいです
image

**Comment by Seasawher** [comment]
@34j 短くしました

**Comment by 34j** [comment]
Seems like it might be better to rewrite the description in English as a Japanese sentence seems to be considered as a single word

**Pull request merged**
